CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
CREATE DATABASE IF NOT EXISTS `fineract_default`;
CREATE DATABASE IF NOT EXISTS `iConsentDDExP`;
CREATE DATABASE IF NOT EXISTS `iConsentDataProvider`;

GRANT ALL ON *.* TO 'iconsent'@'%';
