apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30306
  selector:
    app: mysql
    #tier: mysql
    #clusterIP: None
  #type: NodePort
  #type: ClusterIP
  type: LoadBalancer
